development:
  adapter: postgresql
  encoding: unicode
  database: Shop_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Shop_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Shop_production
  pool: 5
  username: postgres
  password:
